### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by odahoda** [Sundin/Tome-of-Forbidden-Spells#5]
Hi,

I came across this repo while searching for some random song title generator.
I would like to use it (just the data files) for an open source (GPL) project of mine, but for that I need to know how your work is licensed.

Would you mind picking a license of your choice and add some LICENSE file to the repo?

Thanks,
-Ben

**Comment by Sundin** [comment]
Hi @odahoda, nice of you to dig up this old corpse! I have added a MIT license so knock yourself out. 

Cheers from Sweden.
Metal on Metal!
